# Generated by Django 4.2.8 on 2023-12-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pibNewsChannel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodelname',
            name='datetime',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
