# Generated by Django 4.2.8 on 2023-12-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pibNewsChannel', '0006_yourmodelname_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModelName',
            new_name='pibVideo',
        ),
    ]
